spring:
  datasource:
    url: jdbc:mysql://3.38.169.63:3306/daylog
    username: root
    password: 4883
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

jwt:
  expiration_time: 86400000 # 1일 (밀리초)
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
